package cm.te.assignment.a;

public class mulitiplecatchblock {
	public static void main(String[] args) {  
        
        try{    
             int a[]=new int[4];    
             
             System.out.println(a[5]);  
            }    
            catch(ArithmeticException e)  
               {  
                System.out.println("Arithmetic Exception occurs");  
               }    
            catch(ArrayIndexOutOfBoundsException e)  
               {  
                System.out.println("ArrayIndexOutOfBounds Exception occurs");  
               }    
            catch(Exception e)  
               {  
                System.out.println("Parent Exception occurs");  
               }             
            System.out.println("rest of the code");    
 }  
} 



output:

ArrayIndexOutOfBounds Exception occurs
rest of the code
